### ISSUE TITLE
Error in backward encoding

### ISSUE THREAD

**Issue by bhrousseau** [einar-saukas/ZX0-Java#1]
I have made some unit tests in backward mode and found this issue :

Input file data :
FF FE FD

Java encoder (-c -f -b) result :
DA FF FE FD AA A0

Win encoder (-c -f -b) result :
A0 AA FF FE FD DA

I assume the win encoder result is the good one :

```
 DA                 | AA        | A0
(110)       (1 1010 | 1010 1010 | 1010 0) 000
(011)	    (1 0000 | 0000 0000 | 0000 1) 010 (step 1 neg odd bits ?)
(011)       (1 0000 | 0000 1000 | 0000 0) 010 (step 2 deinterlace elias)
LITERAL_LEN EOF__________________________ PAD
```

**Comment by einar-saukas** [comment]
Sorry, it was a silly mistake. Thanks a lot for reporting it! It's fixed now.
